# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(help_text='Choice text', max_length=200)),
                ('votes', models.IntegerField(default=0, help_text='Votes for this choice')),
            ],
            options={
                'verbose_name': 'Choice: Answer for a question',
                'verbose_name_plural': 'Answers for questions',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(help_text='Question text', max_length=200)),
                ('pub_date', models.DateTimeField(help_text='Publication date', verbose_name='date published')),
            ],
            options={
                'verbose_name': 'Question: A question of a poll',
                'verbose_name_plural': 'Questions of polls',
            },
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(help_text='Related question', on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
